script: make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: snuH+K2wzRo0gZ5zvzMCEdXXCuDGLUNfbviI8VCUFT3N5m8nv4BMabh26j7FAEiXhiq8s1YllUk25wXfxsoMjJvSW4z2UASoEBGVh+whAupxHOpif1+zWWNBE7Q8mvuwsYPhcCbkFvw/+UVDS5nhdnoHrX1gPC9ZljJWTwUdrXs=
  app: macross-presentation-stub01
  on:
    repo: arrancar-technology/macross-presentation-stubulator
    branch: develop
