script: make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: JUFAMvgsOS8HNBktZ+mhtOv90Jl6HLsKFVqIf7c5P6xaof6EOASrTXkfFTibHb9wH5JRWVuKtCcasgL6zk8WTeV9K2qXW1YPNjbD2Hn1Bfb3AeRWjAUQPOuwDZQsiDhbD9FbG7ht1zFTWn1bQ00F8Evub+M6l9DEi1kAuibQr9o=
  app: macross-presentation-stub01
  on:
    repo: arrancar-technology/macross-presentation-stubulator
    branch: develop
